# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Must be disabled for Github Pages
#relative_permalinks: true

# Setup
title:               Cytoscape.js
tagline:             'News and tutorials'
url:                 http://blog.js.cytoscape.org
baseurl:             ''
paginate:            5
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Cytoscape.js
  url:               http://js.cytoscape.org

# Custom vars
version:             1.0.0

# Project info
project:
  home:              http://js.cytoscape.org
  repo:              https://github.com/cytoscape/cytoscape.js
  twitter:           https://twitter.com/cytoscape
  stackoverflow:     http://stackoverflow.com/questions/tagged/cytoscape.js
